apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jardin-ai-metrics
  namespace: jardin-ai
spec:
  endpoints:
  - interval: 30s
    port: 8080-tcp
    scheme: http
  selector: 
    matchLabels:
      app: jardin-ai-metrics-git